#!/usr/bin/env bash
# Project:  ai-project-scaffold
# File:     tools/changelog.sh
# Modified: 2026-08-31
# Version:  0.2.1.20260831.0904
# Purpose:  Derive CHANGELOG.md from the tags, so it cannot disagree with what was released
# Changelog:
#   2026-08-31 v0.2.1.20260831.0904 — #250 same cause as release.sh: the fixture now supplies an identity its children inherit.
#   2026-08-18 v0.2.0.20260818.2121 — Initial. A CHANGELOG.md was the one governance file
#                        this project had no answer for, and the obvious answer -- write one
#                        and keep it updated -- is the answer that has now failed twice here
#                        in a week. The repository status table went stale by six releases,
#                        was hand-corrected WITH A WARNING ATTACHED, and re-staled by twelve
#                        within a day. A hand-maintained changelog would go the same way, and
#                        faster, because nobody reads it during the release they are cutting.
#                        So it is DERIVED: annotated tag messages and release notes are the
#                        source, `--check` fails on drift, and preflight runs the check.
#                        The tag is written by tools/release.sh only after every gate and the
#                        receipt succeeded, which means each entry here is backed by one.
set -euo pipefail

# RESOLVED, BECAUSE THE SELFTEST cd-s AWAY. Invoked as `tools/changelog.sh`, a bare "$0"
# stops resolving the moment anything changes directory — and the first run of the selftest
# failed exactly there, silently, with the write never happening.
SELF="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"

TARGET="${CHANGELOG_FILE:-CHANGELOG.md}"
MODE="${1:---check}"
LIMIT="${CHANGELOG_LIMIT:-40}"

render() {
  printf '# Changelog\n\n'
  printf '_Generated by `tools/changelog.sh --write` from the annotated tags. Do not hand-edit.\n'
  printf 'Each tag is written by `tools/release.sh` only after every gate AND the release\n'
  printf 'receipt succeeded, so every entry below is backed by one — the receipt is attached\n'
  printf 'to the GitHub release and names each gate exit code, the artifact SHA-256 and the\n'
  printf 'CI runs it was checked against._\n\n'
  # NEWEST FIRST, and by the tag's own date rather than by name: a version sort would put
  # 0.9.0 above 0.10.0, which is the defect every hand-rolled version comparison has.
  local tag when subject
  # TWO KEYS, AND THE ORDER OF THE FLAGS IS THE OPPOSITE OF WHAT IT LOOKS LIKE: git makes
  # the LAST --sort the primary key. So creatordate decides, and version-aware refname
  # breaks ties. Both are needed and neither is sufficient:
  #   creatordate alone  — two releases cut in the same second tie, and the tiebreak is
  #                        plain refname order, which put 1.0.0 above 2.0.0. Tonight this
  #                        repository cut seven releases in under two hours.
  #   refname alone      — the 0.9.0-above-0.10.0 defect that every hand-rolled version
  #                        comparison has. `v:` is version-aware and does not have it.
  # A TAG POINTING AT HEAD IS EXCLUDED, and this is the second time tonight this exact
  # principle has had to be applied: A DERIVED FILE CANNOT CONTAIN A FACT THAT COMMITTING
  # IT CREATES. release.sh writes the tag AFTER the commit, so the changelog living in that
  # commit can never name it — and a check that demanded otherwise would be red the instant
  # you released, which is a completely normal moment. A gate red at a normal moment is one
  # people learn to ignore, which is how the status block got here.
  # The entry appears on the next release, when that tag no longer points at HEAD.
  # EXCLUDE FIRST, THEN LIMIT. Dropping the HEAD tag after `head -N` silently returns N-1
  # entries, so the file and a fresh render disagree by one at the far end of the window --
  # a drift with no cause a reader could ever find.
  # SKIP_HEAD_TAG is set only by --check. --write must include EVERY tag: it runs BEFORE
  # the release commit exists, when HEAD is still the PREVIOUS release, and excluding that
  # would drop a past release from the file and then demand it back one commit later.
  local _head _tags; _head="none"
  [ "${SKIP_HEAD_TAG:-0}" = "1" ] && _head="$(git rev-parse HEAD 2>/dev/null || echo none)"
  # `awk NR<=n`, NEVER `head -n`, AND THE REASON IS NOT STYLE. `head` closes the pipe as
  # soon as it has its N lines; the producing loop is killed by SIGPIPE; `set -o pipefail`
  # turns that into a failed pipeline; and the command substitution yields NOTHING. The
  # changelog rendered as a header with zero entries — on THIS repository, which has more
  # tags than the limit, while the fixture had fewer and never reproduced it.
  # awk reads its input to the end, so nothing is ever killed for finishing early.
  #
  # It is worth naming what nearly happened: the first fix I made here was to a DIFFERENT
  # construct that looked guilty, it appeared to work, and it was coincidence. A fix whose
  # mechanism you cannot state is a fix you cannot rely on.
  _tags="$(git tag --sort=-v:refname --sort=-creatordate | while IFS= read -r t; do
             [ -n "$t" ] || continue
             if [ "$(git rev-list -n1 "$t" 2>/dev/null)" = "$_head" ]; then continue; fi
             printf '%s\n' "$t"
           done | awk -v n="$LIMIT" 'NR <= n')"
  printf '%s\n' "$_tags" | while IFS= read -r tag; do
    [ -n "$tag" ] || continue
    when="$(git log -1 --format=%ad --date=short "$tag" 2>/dev/null || echo '')"
    # The annotated tag message if there is one; otherwise the commit subject. Never blank:
    # an entry with a version and no text is a row that looks like data and carries none.
    subject="$(git tag -l --format='%(contents:subject)' "$tag" 2>/dev/null | head -1)"
    # A TAG MESSAGE THAT MERELY REPEATS THE VERSION IS NOT A MESSAGE. `git tag -a X -m X`
    # is the common shape and it produced a changelog whose every entry was its own
    # heading -- a row that looks like data and carries none, which is exactly what the
    # empty-message fallback below was written to prevent and did not catch, because the
    # string was not empty.
    [ "$subject" = "$tag" ] && subject=""
    [ -n "$subject" ] || subject="$(git log -1 --format=%s "$tag" 2>/dev/null || echo '')"
    [ -n "$subject" ] || subject="(no message on this tag)"
    printf '## %s — %s\n\n%s\n\n' "$tag" "$when" "$subject"
  done
}

case "$MODE" in
  --selftest)
    # A FIXTURE MUST NOT DEPEND ON THE MACHINE'S GIT CONFIG (#250). The fixtures below create
    # their commits with an inline `-c user.email=...`, but the SCRIPT UNDER TEST then runs
    # bare git commands -- `git tag -a` needs a committer identity of its own and inherits
    # nothing. On a machine whose identity is configured PER-REPOSITORY rather than globally
    # (an ordinary, careful setup when one machine commits under several identities) the tag
    # was never created and the assertion failed. Nothing in the scaffold says a global
    # identity is required, so the fixture supplies one to its children instead of assuming.
    # Exported, not `git -c`, precisely because the child process is the one that needs it.
    export GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-scaffold-selftest}"
    export GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-selftest@invalid}"
    export GIT_COMMITTER_NAME="${GIT_COMMITTER_NAME:-scaffold-selftest}"
    export GIT_COMMITTER_EMAIL="${GIT_COMMITTER_EMAIL:-selftest@invalid}"
    d="$(mktemp -d)"; fails=0
    R="$d/r"
    git init -q "$R"
    commit() { ( cd "$R" && : > "$1" && git add -A \
                 && git -c user.email=t@t -c user.name=t commit -qm "$2" ) >/dev/null 2>&1; }
    cl() { ( cd "$R" && CHANGELOG_FILE=CHANGELOG.md "$SELF" "$1" ) >/dev/null 2>&1; }

    # A TAG POINTING AT HEAD IS EXCLUDED BY DESIGN, so every fixture below tags and then
    # commits. A changelog cannot name the tag its own commit is about to receive.
    commit f1 "first commit"
    ( cd "$R" && git tag -a 1.0.0 -m "1.0.0 the first one" ) >/dev/null 2>&1
    commit f2 "after the first tag"
    cl --write
    case "$(cat "$R/CHANGELOG.md")" in
      *"1.0.0 the first one"*) echo "  ok   the annotated tag message becomes the entry" ;;
      *) echo "  FAIL the tag message is not in the output"; fails=1 ;;
    esac
    if cl --check; then
      echo "  ok   --check is clean immediately after --write"
    else
      echo "  FAIL --check reports drift right after --write — the gate can never be green"; fails=1
    fi

    # THE RELEASE MOMENT. Tagging HEAD must NOT stale the file that commit carries.
    ( cd "$R" && git tag -a 2.0.0 -m "2.0.0 cut right now" ) >/dev/null 2>&1
    if cl --check; then
      echo "  ok   tagging HEAD does not immediately stale the changelog in that commit"
    else
      echo "  FAIL the gate goes red the instant you release"; fails=1
    fi

    # AND THE NEXT COMMIT DOES, or the exclusion would hide that release forever.
    commit f3 "work after the release"
    if cl --check; then
      echo "  FAIL a released tag never became due — it is hidden permanently"; fails=1
    else
      echo "  ok   the next commit makes it due, which is the whole point"
    fi
    cl --write
    grep -q "2.0.0 cut right now" "$R/CHANGELOG.md" \
      && echo "  ok   and the release appears once its tag is no longer HEAD" \
      || { echo "  FAIL the excluded tag never came back"; fails=1; }

    # NEWEST FIRST. Date decides; version-aware refname breaks the tie when two releases
    # are cut in the same second, which is when plain refname order puts 1.0.0 above 2.0.0.
    case "$(grep -m1 '^## ' "$R/CHANGELOG.md")" in
      "## 2.0.0 "*) echo "  ok   newest release is first" ;;
      *) echo "  FAIL the newest release is not at the top: $(grep -m1 '^## ' "$R/CHANGELOG.md")"; fails=1 ;;
    esac

    # A TAG MESSAGE THAT IS JUST THE VERSION IS NOT A MESSAGE. This is the shape that made
    # the first real run produce a changelog of headings and nothing else.
    commit f4 "the real headline"
    ( cd "$R" && git tag -a 4.0.0 -m "4.0.0" ) >/dev/null 2>&1
    commit f5 "after four"
    cl --write
    case "$(grep -A2 '^## 4.0.0' "$R/CHANGELOG.md")" in
      *"the real headline"*) echo "  ok   a tag message repeating the version falls through to the subject" ;;
      *) echo "  FAIL an entry was its own heading and nothing else"; fails=1 ;;
    esac

    # A LIGHTWEIGHT TAG HAS NO MESSAGE AT ALL, and must not produce a blank entry. Its own
    # commit, so the assertion names a subject only this tag can have — reusing an earlier
    # one made this pass on whichever commit happened to be HEAD.
    commit f6 "lightweight has no message"
    ( cd "$R" && git tag 3.0.0 ) >/dev/null 2>&1
    commit f7 "after three"
    cl --write
    case "$(grep -A2 '^## 3.0.0' "$R/CHANGELOG.md")" in
      *"lightweight has no message"*) echo "  ok   a lightweight tag falls back to the commit subject, never blank" ;;
      *) echo "  FAIL a lightweight tag produced an empty entry"; fails=1 ;;
    esac

    # THE LIMIT MUST NOT EMPTY THE FILE. With more tags than the limit, `head` closes the
    # pipe, SIGPIPE kills the producing loop, pipefail turns that into a failed pipeline and
    # the render comes back EMPTY — which is what happened on the real repository while a
    # fixture with fewer tags than the limit stayed green. This case sets the limit BELOW
    # the tag count on purpose.
    ( cd "$R" && CHANGELOG_FILE=CHANGELOG.md CHANGELOG_LIMIT=2 "$SELF" --write ) >/dev/null 2>&1
    n="$(grep -c '^## ' "$R/CHANGELOG.md" || true)"
    if [ "$n" = "2" ]; then
      echo "  ok   a limit below the tag count yields exactly that many entries, not zero"
    else
      echo "  FAIL CHANGELOG_LIMIT=2 produced $n entries"; fails=1
    fi

    rm -rf "$d"
    [ "$fails" -eq 0 ] && { echo "changelog: 9/9 passed"; exit 0; }
    echo "changelog: selftest FAILED" >&2; exit 1 ;;
  --write)
    git rev-parse --git-dir >/dev/null 2>&1 || { echo "changelog: not a git repository" >&2; exit 3; }
    render > "$TARGET"
    echo "changelog: $TARGET written"; exit 0 ;;
  --check)
    [ -f "$TARGET" ] || exit 0
    git rev-parse --git-dir >/dev/null 2>&1 || exit 3
    # NO TAGS IS NOT A STALE CHANGELOG. A fresh clone with no tags fetched, or a project
    # that has never released, cannot derive this file -- and a block it cannot derive is
    # not a block that is wrong. Exit 3, the same rule status_block.sh learned the hard way.
    [ -n "$(git tag)" ] || { echo "changelog: CANNOT CHECK — no tags here" >&2; exit 3; }
    # TWO ACCEPTABLE STATES, and the second is the release moment itself.
    #   full          every tag, which is what --write produced before this commit existed
    #   minus HEAD's  the same file one commit later, once release.sh has tagged HEAD
    # A changelog cannot name the tag its own commit is about to receive, so the entry
    # appears at the NEXT release. Tolerating that here is what stops the gate being red at
    # a completely normal moment — and a gate red at a normal moment is one people ignore.
    if diff -q <(render) "$TARGET" >/dev/null 2>&1; then
      echo "changelog: current"; exit 0
    fi
    if diff -q <(SKIP_HEAD_TAG=1 render) "$TARGET" >/dev/null 2>&1; then
      echo "changelog: current (HEAD carries a tag this file predates, as it must)"; exit 0
    fi
    echo "changelog: STALE — run tools/changelog.sh --write" >&2
    diff <(render) "$TARGET" | head -8 >&2 || true
    exit 1 ;;
  *) echo "usage: changelog.sh [--write|--check|--selftest]" >&2; exit 2 ;;
esac
